예외 처리가 필요한 이유
-------------------------------------
- 오류가 발생했을 때, 오류 로그를 남기면 디버깅에 도움이 됩니다.
- 오류가 발생하는 경우, 실행해서는 안 될 코드는 실행하지 않도록, 실행해야 하는 코드는 그래도 실행되도록 해야합니다.

자바에서 외부 리소스 사용 시 주의점
-------------------------------------
- 자바는 GC가 있어서 JVM 메모리에 있는 인스턴스는 자동 해제가 가능합니다.
- 하지만, 외부 연결과 같은 자바 외부 자원은 자동 해제가 되지 않으므로 반드시 반납해줘야 합니다.

반환값을 통한 예외 처리의 문제점
-------------------------------------
- 정상 흐름과 예외 흐름이 섞여 있어서 코드를 한눈에 이해하기가 힘듭니다.
- 그러한 문제를 해결하기 위해서 예외 처리 메커니즘이 존재합니다.

```java
String connectResult = client.connect();
  if (isError(connectResult)) {
    System.out.println("[네트워크 오류 발생] 오류 코드: " + connectResult);
  } else {
    String sendResult = client.send(data);
  if (isError(sendResult)) {
    System.out.println("[네트워크 오류 발생] 오류 코드: " + sendResult);
  }
}
client.disconnect();
```
- 위 코드는 정상 흐름과 실행 흐름이 섞여 있는 경우입니다.
- 이런 경우 코드를 한눈에 파악하기 힘듭니다.

#### 예외(Exception) : 자바의 프로그램 실행 중 발생할 수 있는 예상치 못한 상황을 예외라고 합니다.

자바의 예외 계층 그림
--------------------------------------
![image](https://github.com/user-attachments/assets/c8a57275-44d0-4400-a570-8d6fa9da0bfe)

- Object : 모든 객체의 최상위 부모인 Object는 예외에게도 최상위 부모입니다.
- Throwable : 최상위 예외를 말합니다. 하위에 Exception과 Error가 있습니다.
- Error : 메모리 부족이나 심각한 시스템 오류처럼 애플리케이션에서 복구가 불가능한 시스템 예외입니다. ( 개발자가 잡으려 하면 안됩니다. )
- Exception : 체크 예외이자, 애플리케이션 로직에서 사용할 수 있는 실질적인 최상위 예외입니다. 하위 예외도 RuntimeException을 제외하고는 모두 체크 예외입니다.
- RuntimeExcpetion : 컴파일러가 체크하지 않는 언체크 예외입니다. RuntimeException과 그 자식 예외는 모두 런타임 예외입니다.

체크 예외 vs 언체크 예외(런타임 예외)
---------------------------------------------
- 체크 예외 : 발생한 예외를 개발자가 명시적으로 처리해야 하는 경우 체크 예외라고 합니다. -> 처리하지 않을 시 컴파일 오류가 발생합니다.
- 언체크 예외 : 개발자가 발생한 예외를 명시적으로 처리하지 않아도 되는 예외를 말합니다.

예외 처리의 주의점
--------------------------------
- 상속 관계에서 부모 타입이 자식을 담을 수 있듯, 예외 처리에서도 상위 예외를 catch로 잡으면 그 하위 예외까지 같이 잡혀버립니다.
- 그래서 Throwable 예외를 잡아서는 안됩니다. -> 보통 Exception부터 필요한 예외로 생각하고 잡으면 됩니다.

예외의 기본 규칙(폭탄돌리기)
-----------------------------------
- 예외는 폭탄 돌리기와 같습니다.
- 예외를 받아서 처리하거나, 처리할 수 없다면 밖으로 던져야 합니다.
- 던질 때도 마찬가지로 Exception을 throws로 던진다면, 그 하위 예외들도 모두 던질 수 있습니다.
- 참고로 예외를 처리하지 못하고 계속 던지다 보면 main() 밖으로 예외를 던지게 되고, 그러면 예외 로그를 출력하면서 시스템이 종료됩니다.

#### 체크 예외 : 잡아서 처리하거나 밖으로 던져야 합니다.

![image](https://github.com/user-attachments/assets/004a06fd-a821-48d7-a77e-e3af99680896)

- super(message)로 전달한 예외는 Throwable에 있는 detailMessage에 보관되며, getMessage()를 통해 조회할 수 있습니다.

체크 예외의 장단점
--------------------------------------------
- 장점 : 개발자가 실수로 예외를 누락하지 않도록 컴파일러가 체크해주는 안전 장치의 역할을 합니다.
- 단점 : 개발자가 모든 체크 예외를 반드시 잡거나 던지도록 처리해야 하므로 번거롭습니다.

#### 언체크 예외 : 예외를 잡아서 처리하지 않고, throws 키워드를 생략해도 자동으로 예외를 던집니다.
- 물론 필요한 경우, 예외를 잡아서 처리해도 됩니다.
- 단, 생략해도 되지만 중요한 예외라면 메서드에 throws를 써서 선언해두면 코드를 호출하는 개발자가 IDE를 통해 편하게 인지할 수 있습니다.

언체크 예외의 장단점
--------------------------------------------
- 장점 : 신경 쓰고 싶지 않은 언체크 예외를 무시할 수 있습니다.
- 단점 : 개발자가 실수로 예외를 누락할 수 있습니다.

main 밖으로 예외가 던져질 시 발생하는 상황
-----------------------------------------------
- 예외 메시지와 예외를 추적할 수 있는 스택 트레이스를 출력하고, 프로그램을 종료합니다.
![image](https://github.com/user-attachments/assets/75f1d44f-51a9-4e70-954a-44252f4eae9d)

정상 흐름과 예외 흐름이 분리된 코드 예시
------------------------------------------
```java
try {
  client.connect();
  client.send(data);
  client.disconnect(); //예외 발생시 무시
} catch (NetworkClientExceptionV2 e) {
  System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
}
```

- 위 코드는 정상 흐름은 try 블럭 내에, 예외 부분은 catch 블럭에서 진행 및 해결됩니다.
- 정상 흐름과 예외 흐름이 블럭으로 명확히 분리되었습니다.
- 하지만, 이런 경우에도 자원 반환은 이루어지지 않습니다.

흐름 분리 + 자원 반납이 추가된 코드 예시
----------------------------------------
```java
try {
  client.connect();
  client.send(data); // RuntimeException이 발생하고, 예외가 밖으로 던져집니다.
} catch (NetworkClientExceptionV2 e) {
  System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
}
  client.disconnect(); // 그렇게 되면 이 코드는 호출되지 않습니다.
```

- 이렇게 하면 흐름도 분리되었고 자원도 반납될 것처럼 보입니다.
- 그렇지만, catch에서 잡을 수 없는 예외가 발생한다면 client.disconnect()가 호출되지 않을 수 있습니다.

자바의 finally의 도입
--------------------------------------------------------
- finally는 자바에서 어떤 경우라도 호출되게 됩니다.
- 그래서 주로 try에서 사용한 자원을 해제할 때 주로 사용됩니다.

```java
try {
  //정상 흐름
} catch {
  //예외 흐름
} finally {
  //반드시 호출해야 하는 마무리 흐름
}
```
- try~catch~finally 구조는 정상 흐름, 예외 흐름, 마무리 흐름을 제공합니다.
- try를 시작하기만 하면 finally는 반드시 호출됩니다.
- try, catch에서 잡을 수 없는 예외가 발생해도 finally는 반드시 호출됩니다.
- finally 코드 블럭이 끝나고 나야 예외가 밖으로 호출됩니다.

try ~ finally
------------------------------------
- 예외를 직접 잡아서 처리할 일이 없다면 try ~ finally만 catch 없이 사용할 수 있습니다.
- 이 때도, 예외를 밖으로 던지는 경우에도 finally 호출이 보장됩니다.
```java
try {
  client.connect();
  client.send(data);
} finally {
  client.disconnect();
}
```

예외의 계층화
--------------------------------------------------
- 예외는 객체이므로 부모 예외를 잡거나 던지면 자식 예외도 함께 잡거나 던질 수 있습니다.
- 특정 예외를 잡아서 처리하고 싶으면 하위 예외를 잡아서 처리하면 됩니다.

![image](https://github.com/user-attachments/assets/30e4c605-6ba8-474e-920b-ef8d081dbee5)

예외 처리 순서의 핵심
------------------------------------
- 모든 예외를 잡아서 처리하려면 Exception을 마지막에 두면 됩니다.
- 하지만, 예외가 발생하면 catch를 순서대로 실행하기 때문에 더 디테일한 자식을 먼저 잡도록 합니다.

여러 예외를 한 번에 잡기
--------------------------------
```java
try {
  client.connect();
  client.send(data);
} catch (ConnectExceptionV3 | SendExceptionV3 e) {
  System.out.println("[연결 또는 전송 오류] 주소: , 메시지: " + e.getMessage());
} finally {
  client.disconnect();
}
```
- 여러 예외를 한 번에 잡을 때는 |를 사용해서 한 번에 잡을 수 있습니다.
- 하지만, 이 때 e로는 각 예외들의 공통 부모의 기능만 사용할 수 있습니다.

예외 처리 키워드
-----------------------------
- throw : throw new 예외()로 새 예외를 발생시킵니다.
- throws : throws 예외클래스를 통해 예외를 밖으로 던집니다.
- try ~ catch : try 블럭에서 발생하는 예외를 잡아서 catch로 넘깁니다. ( catch의 대상에 잡은 예외가 없다면 밖으로 던져야 합니다. ) / catch에서 잡아야 이후 코드를 실행합니다.
- try ~ catch ~ finally : try~catch에서 잡지 못한 예외가 발생해도 finally는 반드시 호출되게 됩니다.

실무에서 예외 처리 방안
-------------------------------------------------
- 처리할 수 없는 예외 : 시스템 오류 때문에 발생한 예외들은 잡아도 해결할 수 없는 경우가 많습니다. 이런 경우 웹이라면 오류 페이지를 보여주고, 개발자를 위해 오류 로그를 남기는 것이 좋습니다.
  
![image](https://github.com/user-attachments/assets/67185eca-f7c1-48fd-917e-c2f8029ef20a)
- 위 사진처럼 체크 예외를 많이 사용하게 되면 처리해야 하는 예외, 던져야 하는 예외의 가짓수로 인해 개발자의 부담이 급격히 증가합니다.

throws Exception의 문제점
------------------------------------------
- 개발자가 다룰 수 없는 많은 체크 예외에 마주하면 throws Exception이라는 코드를 넣으면 되지 않을까 생각이 들 수도 있습니다.
- 그렇지만 그렇게 Exception을 던져버리면 모든 체크예외를 다 밖으로 던지는 것이 됩니다.
- 이는 다른 체크 예외를 체크하지 못하게 해서 중요한 체크 예외를 다 놓쳐버리게 만들기 쉽상입니다.

예외의 공통 처리
-------------------------------------------
- 처리할 수 없는 예외들은 중간에 여러곳에서 나누어 처리하는 것보다, 예외를 공통으로 처리할 수 있는 곳을 만들어서 한 곳에 처리하는 것이 좋습니다.
- 이렇게 하면 개발자가 처리할 수 없는 코드는 생각하지 않고, 본인 스스로의 코드에 더 집중할 수 있게 됩니다.

```java
try {
  networkService.sendMessage(input);
} catch (Exception e) { // 모든 예외를 잡아서 처리
  exceptionHandler(e);
}

//공통 예외 처리
private static void exceptionHandler(Exception e) {
  //공통 처리
  System.out.println("사용자 메시지: 죄송합니다. 알 수 없는 문제가 발생했습니다.");
  System.out.println("==개발자용 디버깅 메시지==");
  e.printStackTrace(System.out); // 스택 트레이스 출력
  // e.printStackTrace(); // System.err에 스택 트레이스 출력
  //필요하면 예외 별로 별도의 추가 처리 가능
  if (e instanceof SendExceptionV4 sendEx) {
    System.out.println("[전송 오류] 전송 데이터: " + sendEx.getSendData());
  }
}
```
- Exception을 잡아서 해결못한 모든 예외를 공통으로 처리합니다.
- 공통 처리 메서드인 exceptionHandler(e)에 예외 객체를 전달합니다.

exceptionHandler() 
------------------------------------
- 해결할 수 없는 예외 발생 시 사용자에게 시스템 내에 알 수 없는 문제가 발생했다고 알리는 것이 좋습니다.
- 개발자는 빠른 디버깅을 위해 오류 로그를 남겨놔야 합니다.
- 예외도 객체이므로 필요하면 instanceof 처럼 예외 객체의 타입을 확인해서 별도의 추가 처리도 할 수 있습니다.

e.printStackTrace()와 출력 로그 남기기
---------------------------------------
- System.err로 출력하면 IDE에서는 출력 결과를 빨간색으로 보여줍니다.
- 그러나, 실무에서는 보통 콘솔 출력이 아닌 Slf4J, logback 같은 별도의 라이브러리를 통해 콘솔과 파일에 함께 결과를 출력하게 됩니다.
- e.printStackTrace()는 직접 호출 시 결과가 콘솔에만 출력된다는 단점이 있습니다.
- 서버에서는 로그를 파일로 확인해야 하기에, 보통은 로그 라이브러리를 통해서 예외 스택 트레이스를 출력합니다.

try ~ with ~ resources
-------------------------------------------
- 자바 7부터 도입된 기능으로, try에서 자원을 함께 사용한다는 뜻입니다.
- AutoCloseable 인터페이스를 구현해야만 해당 기능을 사용할 수 있습니다.

```java
package java.lang;

public interface AutoCloseable {
    void close() throws Exception;
}
```

```java
package exception.ex4;
public class NetworkServiceV5 {

  public void sendMessage(String data) {
    String address = "https://example.com";
    try (NetworkClientV5 client = new NetworkClientV5(address)) {
    client.initError(data);
    client.connect();
    client.send(data);
  } catch (Exception e) {
    System.out.println("[예외 확인]: " + e.getMessage());
    throw e;
  }
}
}
```
- close()는 AutoCloseable 인터페이스가 제공하는 메서드로 try가 끝나면 자동으로 호출됩니다.
- 종료 시점에 자원을 반납하는 방법을 여기에 정의하면 됩니다.
- try 괄호 안에 사용할 자원을 명시하면, try 블럭이 끝나면 자동으로 AutoCloseable.close()를 호출해서 자원을 해제합니다.
- 참고로 catch 블럭 없이 try 블럭만 있어도 close()는 호출됩니다.

Try with resources의 장점
---------------------------------------
- 리소스의 누수를 방지합니다. ( 모든 리소스가 제대로 닫히도록 보장합니다. )
- 코드의 간결성 및 가독성을 향상시킵니다.
- 스코프의 범위를 한정 짓습니다.
- 자원해제가 조금 더 빨리 이루어집니다.
